[package]
name = "thallium-store-backend"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
store-catalog = { path = "../store-catalog" }
store-core = { path = "../store-core" }
store-db = { path = "../store-db" }
store-uni = { path = "../store-uni" }
reqwest.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

